version: '3.3'
services:
  postgres:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      -
        type: bind
        source: ./persistence
        target: /var/lib/postgresql/data